package gyurix.icicles.enums;

import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.math.Rectangle;
import com.badlogic.gdx.math.Vector2;

/**
 * Created by GyuriX on 2017. 08. 16..
 */

public class Constants {
    public static final Color HUD_FONT_COLOR = Color.YELLOW;
    public static final Color LOADING_BACKGROUND = new Color(0f, 0f, 0f, 1f);
    public static final Color LOADING_COLOR = new Color(1f, 1f, 0.2f, 1f);
    public static final Color LOADING_DONE_COLOR = new Color(0f, 1f, 0f, 1f);
    public static final Color LOADING_LEFT_COLOR = new Color(0.2f, 0.2f, 0.2f, 1f);
    public static final Color MENU_INFO_TEXT_COLOR = new Color(0.2f, 0.2f, 0.8f, 1f);
    public static final Color MENU_TEXT_COLOR = Color.YELLOW;
    public static final Color PAUSE_COUNT_COLOR = new Color(0f, 1f, 1f, 1f);
    public static final Color PAUSE_DESC_COLOR = new Color(1f, 0.3f, 0.3f, 1f);
    public static final Color PAUSE_TITLE_COLOR = new Color(1f, 0f, 0f, 1f);
    public static final Color GAME_OVER_COLOR = new Color(1f, 0.5f, 0f, 1f);
    public static final Color PLAYER_COLOR = new Color(1f, 1f, 0f, 0.9f);
    public static final Color SHOP_DESC_COLOR = new Color(0.5f, 1f, 1f, 1f);
    public static final Color SHOP_DESC_PRICE_COLOR = new Color(1f, 1f, 0f, 1f);
    public static final Color SHOP_DESC_TITLE_COLOR = new Color(1f, 0.7f, 0f, 1f);
    public static final Color SHOP_ITEM_COUNT_COLOR = new Color(0, 1f, 1f, 0.9f);
    public static final Color SHOP_TITLE_COLOR = new Color(1f, 0.7f, 0f, 1f);
    public static final Color STORY_TITLE_COLOR = new Color(0f, 0.6f, 0f, 1f);
    public static final Color[] COIN_ICE_COLOR = new Color[]{new Color(1f, 1f, 0.5f, 0.9f), new Color(1f, 1f, 0.7f, 0.9f), new Color(1f, 1f, 1f, 0.9f)};
    public static final Color[] HARD_ICE_COLOR = new Color[]{new Color(1f, 0f, 0f, 0.9f), new Color(0.5f, 0f, 0f, 0.9f), new Color(1f, 0f, 0f, 0.9f)};
    public static final Color[] ICE_COLOR = new Color[]{new Color(0f, 1f, 1f, 0.9f), new Color(0.5f, 1f, 1f, 0.9f), new Color(1f, 1f, 1f, 0.9f)};
    public static final float DIFFICULTY_ICON_SEP = 16f;
    public static final float DIFFICULTY_ICON_SIZE = 128f;
    public static final float GRAVITY = -200;
    public static final float HUD_BUTTON_SEP = 16f;
    public static final float HUD_ITEM_SIZE = 96f;
    public static final float HUD_ITEM_SEP = 24f;
    public static final float HUD_BUTTON_SIZE = 64f;
    public static final float HUD_FONT_SCALE = 0.75f;
    public static final float HUD_ICON_SEP = 10f;
    public static final float HUD_LINE_SEP = 16f;
    public static final float ICON_SIZE = 48f;
    public static final float INITIAL_GRAVITY_RANGE = 1000;
    public static final float LOADING_SCALE = 1.5f;
    public static final float MAX_ICE_X_SIZE = 80;
    public static final float MAX_ICE_Y_SIZE = 120;
    public static final float MENU_BOX_SCALE = 0.7f;
    public static final float MENU_BOX_WIDTH = 10f;
    public static final float MENU_INFO_TEXT_SCALE = 1.2f;
    public static final float MIN_ICE_X_SIZE = 80;
    public static final float MIN_ICE_Y_SIZE = 100;
    public static final float PAUSE_CD = 3f;
    public static final float PAUSE_COUNT_SCALE = 3f;
    public static final float PAUSE_DESC_SCALE = 1.2f;
    public static final float PAUSE_TITLE_SCALE = 2f;
    public static final float GAME_OVER_SCALE = 2f;
    public static final float PLAYER_ACM_MOVEMENT_SENSIBILITY = 50f;
    public static final float PLAYER_BODY_WIDTH = 30f;
    public static final float PLAYER_BUTTON_MOVEMENT_SENSIBILITY = 50f;
    public static final float PLAYER_HAND_DISTANCE = 50f;
    public static final float PLAYER_HAND_HEIGHT = 150f;
    public static final float PLAYER_HAND_WIDTH = 15f;
    public static final float PLAYER_HEAD_SIZE = 100f;
    public static final float PLAYER_LEG_DISTANCE = 50f;
    public static final float PLAYER_LEG_HEIGHT = 70f;
    public static final float PLAYER_LEG_WIDTH = 20f;
    public static final float PLAYER_MAX_VELOCITY = 1000f;
    public static final float PLAYER_MOVEMENT_DRAG = 4f;
    public static final float PLAYER_SIZE = 300f;
    public static final float SHOP_DESC_SCALE = 0.7f;
    public static final float SHOP_DESC_TITLE_SCALE = 1f;
    public static final float SHOP_DESC_PRICE_SCALE = 0.85f;
    public static final float SHOP_DESC_WIDTH = 500f;
    public static final float SHOP_FRAME_SIZE = 160f;
    public static final float SHOP_FRAME_XSEP = 48f;
    public static final float SHOP_FRAME_YSEP = 48f;
    public static final float SHOP_ITEM_COUNT_SCALE = 0.7f;
    public static final float SHOP_ITEM_SIZE = 128f;
    public static final float SHOP_BUY_ICON_SIZE = 64f;
    public static final float SHOP_TITLE_SCALE = 1.2f;
    public static final float STORY_TITLE_SCALE = 1.2f;
    public static final float WORLD_HEIGHT = 900;
    public static final float WORLD_WIDTH = 1600;
    public static final int PLAYER_LIFE = 5;
    public static final int SHOP_ITEM_COLUMNS = 4;
    public static final int SHOP_ITEM_ROWS = 3;
    public static final Rectangle LOADING_BAR = new Rectangle(100, 100, 1400, 100);
    public static final Rectangle MENU_BOX_CONTROL = new Rectangle(400, 100, 800, 80);
    public static final Rectangle MENU_BOX_SHOP = new Rectangle(400, 200, 800, 80);
    public static final Rectangle MENU_BOX_PLAY = new Rectangle(400, 300, 800, 80);
    public static final Rectangle MENU_BOX_STORY = new Rectangle(400, 400, 800, 80);
    public static final Vector2 SHOP_DESC = new Vector2(1000, 570);
    public static final Vector2 SHOP_DESC_BUY = new Vector2(1420, 110);
    public static final Vector2 SHOP_DESC_PRICE = new Vector2(1010, 160);
    public static final Vector2 SHOP_DESC_TITLE = new Vector2(1010, 660);
    public static final Vector2 SHOP_FIRST_ITEM = new Vector2(100, 500);
    public static final float GAME_OVER_ICON_SIZE = 128;
    public static final float GAME_OVER_SMILEY_ICON_SIZE = 196;
    public static float SHOP_CLOSE_X = 1500f;
    public static float SHOP_CLOSE_Y = 800f;
    public static float LEVEL_CIRCLE_RADIUS = 48f;
    public static float LEVEL_CIRCLE_OUTLINE_WIDTH = 8f;
    public static Color LEVEL_CIRCLE_INNER_COLOR = new Color(1f,1f,1f,0.4f);
    public static Color LEVEL_CIRCLE_OUTLINE_COLOR =new Color(0.5f,0.3f,0.1f,0.8f);
}
